name: 'medicare_saf_connector'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'                      # configuration required

vars:
  input_database: medicare_lds_saf      # configuration required
                                        # name of the database where sources feeding this project are stored

  input_schema:  saf                    # configuration required
                                        # name of the schema where sources feeding this project is stored

  output_database: tuva                 # configuration required
                                        # name of the database where output of this project should be written

  output_schema: claims_input           # configuration required
                                        # name of the schema where output of this project should be written

  carrier_base_claim: "{{ source('saf','carrier_base_claim') }}"
  carrier_claim_line: "{{ source('saf','carrier_claim_line') }}"
  dme_base_claim: "{{ source('saf','dme_base_claim') }}"
  dme_claim_line: "{{ source('saf','dme_claim_line') }}"
  hha_base_claim: "{{ source('saf','hha_base_claim') }}"
  hha_revenue_center: "{{ source('saf','hha_revenue_center') }}"
  hospice_base_claim: "{{ source('saf','hospice_base_claim') }}"
  hospice_revenue_center: "{{ source('saf','hospice_revenue_center') }}"
  inpatient_base_claim: "{{ source('saf','inpatient_base_claim') }}"
  inpatient_revenue_center: "{{ source('saf','inpatient_revenue_center') }}"
  master_beneficiary_summary: "{{ source('saf','master_beneficiary_summary') }}"
  outpatient_base_claim: "{{ source('saf','outpatient_base_claim') }}"
  outpatient_revenue_center: "{{ source('saf','outpatient_revenue_center') }}"
  snf_base_claim: "{{ source('saf','snf_base_claim') }}"
  snf_revenue_center: "{{ source('saf','snf_revenue_center') }}"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  medicare_saf_connector:
    +materialized: view
    core:
      +materialized: table