name: 'medicare_lds_connector'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.2.0"


profile: 'default'                      



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  medicare_lds_connector:
    +materialized: view
    core:
      +materialized: table