select
      desy_sort_key
    , reference_year
    , sample_group
    , state_code
    , county_code
    , state_cnty_fips_cd_01
    , state_cnty_fips_cd_02
    , state_cnty_fips_cd_03
    , state_cnty_fips_cd_04
    , state_cnty_fips_cd_05
    , state_cnty_fips_cd_06
    , state_cnty_fips_cd_07
    , state_cnty_fips_cd_08
    , state_cnty_fips_cd_09
    , state_cnty_fips_cd_10
    , state_cnty_fips_cd_11
    , state_cnty_fips_cd_12
    , sex_code
    , race_code
    , age
    , orig_reason_for_entitlement
    , curr_reason_for_entitlement
    , esrd_indicator
    , mdcr_status_code_01
    , mdcr_status_code_02
    , mdcr_status_code_03
    , mdcr_status_code_04
    , mdcr_status_code_05
    , mdcr_status_code_06
    , mdcr_status_code_07
    , mdcr_status_code_08
    , mdcr_status_code_09
    , mdcr_status_code_10
    , mdcr_status_code_11
    , mdcr_status_code_12
    , part_a_termination_code
    , part_b_termination_code
    , entitlement_buy_in_ind1
    , entitlement_buy_in_ind2
    , entitlement_buy_in_ind3
    , entitlement_buy_in_ind4
    , entitlement_buy_in_ind5
    , entitlement_buy_in_ind6
    , entitlement_buy_in_ind7
    , entitlement_buy_in_ind8
    , entitlement_buy_in_ind9
    , entitlement_buy_in_ind10
    , entitlement_buy_in_ind11
    , entitlement_buy_in_ind12
    , hmo_indicator1
    , hmo_indicator2
    , hmo_indicator3
    , hmo_indicator4
    , hmo_indicator5
    , hmo_indicator6
    , hmo_indicator7
    , hmo_indicator8
    , hmo_indicator9
    , hmo_indicator10
    , hmo_indicator11
    , hmo_indicator12
    , hi_coverage
    , smi_coverage
    , hmo_coverage
    , state_buy_in_coverage
    , valid_date_of_death_switch
    , date_of_death
    , dual_stus_cd_01
    , dual_stus_cd_02
    , dual_stus_cd_03
    , dual_stus_cd_04
    , dual_stus_cd_05
    , dual_stus_cd_06
    , dual_stus_cd_07
    , dual_stus_cd_08
    , dual_stus_cd_09
    , dual_stus_cd_10
    , dual_stus_cd_11
    , dual_stus_cd_12
from {{ source('medicare_lds','master_beneficiary_summary') }}