select
      desy_sort_key
    , claim_no
    , clm_thru_dt
    , nch_near_line_rec_ident_cd
    , nch_clm_type_cd
    , clm_disp_cd
    , carr_num
    , carr_clm_pmt_dnl_cd
    , clm_pmt_amt
    , carr_clm_prmry_pyr_pd_amt
    , rfr_physn_upin
    , rfr_physn_npi
    , carr_clm_prvdr_asgnmt_ind_sw
    , nch_clm_prvdr_pmt_amt
    , nch_clm_bene_pmt_amt
    , nch_carr_clm_sbmtd_chrg_amt
    , nch_carr_clm_alowd_amt
    , carr_clm_cash_ddctbl_apld_amt
    , carr_clm_hcpcs_yr_cd
    , carr_clm_rfrng_pin_num
    , prncpal_dgns_cd
    , prncpal_dgns_vrsn_cd
    , icd_dgns_cd1
    , icd_dgns_vrsn_cd1
    , icd_dgns_cd2
    , icd_dgns_vrsn_cd2
    , icd_dgns_cd3
    , icd_dgns_vrsn_cd3
    , icd_dgns_cd4
    , icd_dgns_vrsn_cd4
    , icd_dgns_cd5
    , icd_dgns_vrsn_cd5
    , icd_dgns_cd6
    , icd_dgns_vrsn_cd6
    , icd_dgns_cd7
    , icd_dgns_vrsn_cd7
    , icd_dgns_cd8
    , icd_dgns_vrsn_cd8
    , icd_dgns_cd9
    , icd_dgns_vrsn_cd9
    , icd_dgns_cd10
    , icd_dgns_vrsn_cd10
    , icd_dgns_cd11
    , icd_dgns_vrsn_cd11
    , icd_dgns_cd12
    , icd_dgns_vrsn_cd12
    , dob_dt
    , gndr_cd
    , bene_race_cd
    , bene_cnty_cd
    , bene_state_cd
    , cwf_bene_mdcr_stus_cd
    , clm_bene_pd_amt
    , cpo_prvdr_num
    , cpo_org_npi_num
    , carr_clm_blg_npi_num
    , aco_id_num
from {{ source('medicare_lds','carrier_base_claim') }}