name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'



#vars:


dispatch:
  - macro_namespace: dbt
    search_order: [ 'medicare_saf_connector', 'dbt']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]



target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"



models:
  integration_tests:
    +materialized: ephemeral
#  the_tuva_project:
#    +database: tuva_test
  